CREATE TABLE Students(
StudentID INT PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(100) UNIQUE,
Age INT CHECK(AGE>=17),
GPA DECIMAL(3,2) DEFAULT 0.0,
DeptID INT, 
FOREiGN KEY (DeptID) REFERENCES Departments (DeptID) ON DELETE SET NULL
);